export declare const iw: () => number;
export declare const ih: () => number;
export declare const isSmall: () => boolean;
export declare const isMiddle: () => boolean;
export declare const isLarge: () => boolean;
export declare const isExtraLarge: () => boolean;
export declare const isAndroid: () => boolean;
export declare const isFireFox: () => boolean;
export declare const isChrome: () => boolean;
export declare const isPad: () => boolean;
export declare const isIos: () => boolean;
export declare const isWechat: () => boolean;
export declare const isPc: () => boolean;
export declare const isLow: () => boolean;
export declare const isIPhoneX: () => boolean;
export declare const hair: () => 1 | 0.5;
export declare const line: () => 1 | 0.65;
export declare function getAndroidVersion(): number;
export declare function getIOSVersion(): number;
export declare const isNativeIOS: () => any;
export declare const isNativeAndroid: () => any;
export declare const isNative: () => any;
export declare const safeTop: () => 0 | 43 | 20;
export declare const safeBottom: () => 0 | 25;
export declare const setCanNotScalePage: () => void;
export declare const setKeyboardAutoHide: () => void;
export declare const setCanScrollByAttribute: (dataKey?: string) => void;
export declare const setCanScroll: (view?: any) => void;
